function l(zh: string, en: string) {
  return { zh, en };
}

const seededAt = "2026-07-01T00:00:00.000Z";

export const seedQuotaState = {
  policies: [
    {
      policyId: "qpo_brand_lab_daily_runs",
      workspaceId: "wsp_brand_content",
      workspaceContextKey: "brand-lab",
      packageId: null,
      serviceId: null,
      taskVersionId: null,
      sessionVersionId: null,
      entrySurface: null,
      scopeType: "workspace-context",
      scopeRefId: "brand-lab",
      metric: "daily_runs",
      windowType: "daily",
      limitValue: 24,
      softLimitValue: 12,
      hardLimitValue: 24,
      actionOnSoftLimit: "warn",
      actionOnHardLimit: "require_override",
      status: "active",
      enabled: true,
      priority: 120,
      summary: l("品牌工坊单日实例额度", "Brand-lab daily run quota"),
      notes: "Applies to all runs launched inside the brand-lab workspace context.",
      createdByUserId: null,
      updatedByUserId: null,
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      policyId: "qpo_creator_drama_audit_exports",
      workspaceId: "wsp_brand_content",
      workspaceContextKey: "brand-lab",
      packageId: "creator-drama-suite",
      serviceId: "drama-storyboard",
      taskVersionId: "tsv_drama_storyboard",
      sessionVersionId: "sev_creator_drama_suite",
      entrySurface: null,
      scopeType: "package",
      scopeRefId: "creator-drama-suite",
      metric: "audit_exports",
      windowType: "daily",
      limitValue: 10,
      softLimitValue: 6,
      hardLimitValue: 10,
      actionOnSoftLimit: "warn",
      actionOnHardLimit: "require_override",
      status: "active",
      enabled: true,
      priority: 140,
      summary: l("短剧包审计导出额度", "Drama package audit-export quota"),
      notes: "Soft threshold creates quota events for audit-export activity.",
      createdByUserId: null,
      updatedByUserId: null,
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      policyId: "qpo_creator_drama_browser_minutes",
      workspaceId: "wsp_brand_content",
      workspaceContextKey: "brand-lab",
      packageId: "creator-drama-suite",
      serviceId: "drama-storyboard",
      taskVersionId: "tsv_drama_storyboard",
      sessionVersionId: "sev_creator_drama_suite",
      entrySurface: null,
      scopeType: "package",
      scopeRefId: "creator-drama-suite",
      metric: "browser_minutes",
      windowType: "monthly",
      limitValue: 480,
      softLimitValue: 360,
      hardLimitValue: 480,
      actionOnSoftLimit: "warn",
      actionOnHardLimit: "require_override",
      status: "active",
      enabled: true,
      priority: 110,
      summary: l("短剧包浏览器分钟预算", "Drama package browser-minute budget"),
      notes: "Displayed in Creator cost governance even before full billing ledgers exist.",
      createdByUserId: null,
      updatedByUserId: null,
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      policyId: "qpo_personal_image_credits",
      workspaceId: "wsp_personal",
      workspaceContextKey: "personal",
      packageId: "brand-poster-suite",
      serviceId: "poster-batch",
      taskVersionId: "tsv_poster_batch",
      sessionVersionId: "sev_brand_poster_suite",
      entrySurface: null,
      scopeType: "workspace-context",
      scopeRefId: "personal",
      metric: "image_credits",
      windowType: "monthly",
      limitValue: 100,
      softLimitValue: 80,
      hardLimitValue: 100,
      actionOnSoftLimit: "warn",
      actionOnHardLimit: "require_override",
      status: "active",
      enabled: true,
      priority: 100,
      summary: l("个人空间图像额度", "Personal image-credit quota"),
      notes: "Initial seed policy for poster generation governance.",
      createdByUserId: null,
      updatedByUserId: null,
      createdAt: seededAt,
      updatedAt: seededAt,
    },
  ],
  counters: [],
  events: [],
  overrides: [],
};
