import { mcpStateSchema, type McpState } from "./storage-schema.js";

export const seedMcpState: McpState = mcpStateSchema.parse({
  registry: [
    {
      mcpId: "mcp.browser.playwright",
      workspaceId: null,
      displayName: "Playwright Browser Helper",
      description: "Built-in browser automation bridge for controlled web tasks.",
      source: "first-party",
      transport: "stdio",
      ref: "/usr/local/bin/lingban-playwright-mcp",
      status: "active",
      riskLevel: "high",
      defaultCredentialId: null,
      defaultNetworkPolicyRef: null,
      approvalRequired: true,
      tags: ["browser", "automation", "first-party"],
      createdAt: "2026-07-08T00:00:00.000Z",
      updatedAt: "2026-07-08T00:00:00.000Z",
    },
    {
      mcpId: "mcp.image.gpt-image-2",
      workspaceId: null,
      displayName: "GPT Image 2 Helper",
      description: "Built-in image generation helper wired to GPT Image 2.",
      source: "first-party",
      transport: "stdio",
      ref: "/workspace/mcp/imagegen-helper.js",
      status: "disabled",
      riskLevel: "medium",
      defaultCredentialId: "cred_openai_image_api_key",
      defaultNetworkPolicyRef: "np_image_gpt_image_2",
      approvalRequired: false,
      tags: ["image", "first-party"],
      createdAt: "2026-07-08T00:00:00.000Z",
      updatedAt: "2026-07-08T00:00:00.000Z",
    },
    {
      mcpId: "workspace:seedance-api",
      workspaceId: null,
      displayName: "Seedance Workspace Connector",
      description: "Workspace-managed Seedance API endpoint.",
      source: "workspace-managed",
      transport: "http",
      ref: "https://mcp.workspace.internal/seedance",
      status: "active",
      riskLevel: "medium",
      defaultCredentialId: "cred_seedance_api_key",
      defaultNetworkPolicyRef: "np_seedance_workspace",
      approvalRequired: false,
      tags: ["seedance", "workspace-managed"],
      createdAt: "2026-07-08T00:00:00.000Z",
      updatedAt: "2026-07-08T00:00:00.000Z",
    },
    {
      mcpId: "workspace:notion-sse",
      workspaceId: null,
      displayName: "Notion Workspace SSE",
      description: "Workspace-managed Notion MCP over SSE.",
      source: "workspace-managed",
      transport: "sse",
      ref: "https://mcp.workspace.internal/notion/sse",
      status: "active",
      riskLevel: "medium",
      defaultCredentialId: "cred_workspace_notion_token",
      defaultNetworkPolicyRef: "np_notion_workspace",
      approvalRequired: false,
      tags: ["notion", "workspace-managed"],
      createdAt: "2026-07-08T00:00:00.000Z",
      updatedAt: "2026-07-08T00:00:00.000Z",
    },
    {
      mcpId: "third-party:figma-mcp",
      workspaceId: null,
      displayName: "Figma Third-party MCP",
      description: "External Figma MCP connector managed outside the platform.",
      source: "third-party",
      transport: "sse",
      ref: "https://third-party-mcp.example.org/figma/sse",
      status: "active",
      riskLevel: "high",
      defaultCredentialId: "cred_figma_pat",
      defaultNetworkPolicyRef: "np_figma_external",
      approvalRequired: true,
      tags: ["figma", "third-party"],
      createdAt: "2026-07-08T00:00:00.000Z",
      updatedAt: "2026-07-08T00:00:00.000Z",
    },
    {
      mcpId: "third-party:asset-library",
      workspaceId: null,
      displayName: "Asset Library Connector",
      description: "External asset library connector.",
      source: "third-party",
      transport: "http",
      ref: "https://third-party-mcp.example.org/assets",
      status: "active",
      riskLevel: "high",
      defaultCredentialId: "cred_asset_library_api_key",
      defaultNetworkPolicyRef: "np_asset_library_external",
      approvalRequired: true,
      tags: ["asset-library", "third-party"],
      createdAt: "2026-07-08T00:00:00.000Z",
      updatedAt: "2026-07-08T00:00:00.000Z",
    },
  ],
  bindings: [],
  networkPolicies: [
    {
      policyRef: "np_seedance_workspace",
      workspaceId: null,
      displayName: "Seedance Workspace Egress",
      description: "Allow Seedance workspace-managed MCP traffic to the internal workspace gateway.",
      status: "active",
      mode: "allowlist",
      allowedProtocols: ["https"],
      allowedHostPatterns: ["mcp.workspace.internal"],
      allowedPorts: [443],
      allowedPathPrefixes: ["/seedance"],
      requireTls: true,
      blockPrivateNetwork: false,
      tags: ["workspace-managed", "seedance"],
      createdAt: "2026-07-09T00:00:00.000Z",
      updatedAt: "2026-07-09T00:00:00.000Z",
    },
    {
      policyRef: "np_notion_workspace",
      workspaceId: null,
      displayName: "Notion Workspace Egress",
      description: "Allow Notion SSE MCP traffic to the internal workspace gateway.",
      status: "active",
      mode: "allowlist",
      allowedProtocols: ["https"],
      allowedHostPatterns: ["mcp.workspace.internal"],
      allowedPorts: [443],
      allowedPathPrefixes: ["/notion"],
      requireTls: true,
      blockPrivateNetwork: false,
      tags: ["workspace-managed", "notion"],
      createdAt: "2026-07-09T00:00:00.000Z",
      updatedAt: "2026-07-09T00:00:00.000Z",
    },
    {
      policyRef: "np_figma_external",
      workspaceId: null,
      displayName: "Figma External Egress",
      description: "Allow the governed Figma third-party MCP endpoint.",
      status: "active",
      mode: "allowlist",
      allowedProtocols: ["https"],
      allowedHostPatterns: ["third-party-mcp.example.org"],
      allowedPorts: [443],
      allowedPathPrefixes: ["/figma"],
      requireTls: true,
      blockPrivateNetwork: true,
      tags: ["third-party", "figma"],
      createdAt: "2026-07-09T00:00:00.000Z",
      updatedAt: "2026-07-09T00:00:00.000Z",
    },
    {
      policyRef: "np_asset_library_external",
      workspaceId: null,
      displayName: "Asset Library External Egress",
      description: "Allow the governed asset library third-party MCP endpoint.",
      status: "active",
      mode: "allowlist",
      allowedProtocols: ["https"],
      allowedHostPatterns: ["third-party-mcp.example.org"],
      allowedPorts: [443],
      allowedPathPrefixes: ["/assets"],
      requireTls: true,
      blockPrivateNetwork: true,
      tags: ["third-party", "assets"],
      createdAt: "2026-07-09T00:00:00.000Z",
      updatedAt: "2026-07-09T00:00:00.000Z",
    },
  ],
  healthSnapshots: [],
});
